Error handling fix.
nodestream-proj/nodestream pull request #244
Opened 2024-01-29 23:03 UTC by angelosantos4

2024-01-29 23:41 UTC, zprobst commented on nodestream/pipeline/pipeline.py
> +        if self.pipeline_has_died():
I was expecting this to be in the loop before the await. What was the logic behind putting this in the head?

2024-01-30 16:03 UTC, zprobst approved these changes

2024-01-30 16:04 UTC, zprobst requested changes
Looks like these tests are flaky. Can you take a look?

2024-01-30 17:47 UTC, ccloes approved these changes
Reviewed as a team during standup, waiting for Zach's review

2024-01-30 18:51 UTC, ccloes approved these changes
Still waiting on Zach's review.

2024-01-30 19:02 UTC, zprobst approved these changes

2024-01-30 19:06 UTC, merged